const jsonServer = require("json-server");
const database = require("./database/index");

/**
 * An instance of express server created by json-server
 */
const server = jsonServer.create();

/**
 * Dummy data generated by Faker
 */
const data = database.createData();
const router = jsonServer.router(data);

// Define middlewares

const middlewares = jsonServer.defaults();

// Apply various settings to the server instance

server.use(middlewares);
server.use(router);

// Start the server and listen to port 3000

server.listen(3000, () => {
  console.log("JSON Server is running");
});
