const jsonServer = require("json-server");
const auth = require("json-server-auth");
const cors = require("cors");
const database = require("./database/index");

/**
 * An instance of express server created by json-server
 */
const app = jsonServer.create();

/**
 * Dummy data generated by Faker
 */
const data = database.createData();
const router = jsonServer.router(data);

// Bind the JSON Server router db

app.db = router.db;

// Get default middleware

const middlewares = jsonServer.defaults();

// Configure the express server

app.use(cors());
app.use(auth);
app.use(middlewares);
app.use(router);

// Start the server and listen to port 3000

app.listen(3000, () => {
  console.log("JSON Server is running");
});
